#ifndef CONSTANTS_H
#define CONSTANTS_H

// Window/Screen
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define VIRTUAL_WIDTH 432
#define VIRTUAL_HEIGHT 243

#define TARGET_FPS 30

// Fonts size
#define FONT_SMALL 8
#define FONT_MEDIUM 16
#define FONT_LARGE 32

// Game
#define GAME_TITLE "BREAKOUT"
#define OPTION_START "START"
#define OPTION_HIGH_SCORES "HIGH SCORES"

// Paddles
#define PADDLE_SMALL_WIDTH 32
#define PADDLE_MEDIUM_WIDTH 64
#define PADDLE_LARGE_WIDTH 96
#define PADDLE_HUGE_WIDTH 128
#define PADDLE_HEIGHT 16

#endif